//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnecdotalRecord
    {
        public int AnecdotalRecordID { get; set; }
        public string StudentUserID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> DateTimeObserved { get; set; }
        public string Place { get; set; }
        public string Observer { get; set; }
        public string BehaviorObserved { get; set; }
        public string Action { get; set; }
        public string Summary { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Counsellor Counsellor { get; set; }
    }
}
