//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public int AnnouncementID { get; set; }
        public Nullable<System.DateTime> AnnouncementDate { get; set; }
        public string AnnouncementTitle { get; set; }
        public string AnnouncementBody { get; set; }
    }
}
