//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appntmnt
    {
        public int Appntmnt_ID { get; set; }
        public string StudentUserID { get; set; }
        public Nullable<System.DateTime> Appntmnt_Date { get; set; }
        public string Appntmnt_Time { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
