//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounsellingContract
    {
        public int CounsellingContractID { get; set; }
        public string StudentUserID { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<bool> StudentAgrees { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
