//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counsellor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Counsellor()
        {
            this.CounsellingForm = new HashSet<CounsellingForm>();
        }
    
        public string UserID { get; set; }
        public string CounsellorID { get; set; }
        public string CounsellorLastName { get; set; }
        public string CounsellorFirstName { get; set; }
        public string CounsellorMiddleName { get; set; }
        public string CounsellorEmail { get; set; }
    
        public virtual AspNetUser AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CounsellingForm> CounsellingForm { get; set; }
    }
}
