//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsychTest
    {
        public int QuestionID { get; set; }
        public string UserID { get; set; }
        public int Answer { get; set; }
    
        public virtual PsychTestQuestion PsychTestQuestion { get; set; }
        public virtual Student Student { get; set; }
    }
}
