//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int StudentID { get; set; }
        public string StudentLastName { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentMiddleName { get; set; }
        public string StudentEmail { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string Address { get; set; }
        public string Sex { get; set; }
        public string Civil_Status__CivilStatus { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<decimal> PhoneNumber { get; set; }
        public string Birthplace { get; set; }
        public string Dialect { get; set; }
        public string Hobbies { get; set; }
        public string BirthRank { get; set; }
        public string UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Course Course { get; set; }
    }
}
